### ISSUE TITLE
V001-CPAGV Case Tests evaluation - Source control management

### ISSUE THREAD

**Issue by clopezno** [lfx1001/avrela#129]
Case study  https://github.com/davidmigloz/go-bees  from 2/11/2017  to 16/10/2017

Case test
CPAGV01_Case 10 - https://github.com/pac1006/GESPRO_GESTIONVERSIONES  09/12/2022 09/12/2022 (2)
CPAGV01_Case 8	- https://github.com/jcm1020/GESPRO_GESTIONVERSIONES  10/12/2022 11/12/2022 (2)
CPAGV01_ Case 7  - https://github.com/jrp1004/GESPRO_GESTIONVERSIONES 13/12/2022 13/12/2022 (3)

**Comment by lfx1001** [comment]
CPAGV01_Case presenta una discrepancia ya que la simulación no considera este merge commit:

[{"sha":"a5aaf9016611f9913c21d1f906d7c75df580529a","node_id":"MDY6Q29tbWl0NjU5Mjc2Nzg6YTVhYWY5MDE2NjExZjk5MTNjMjFkMWY5MDZkN2M3NWRmNTgwNTI5YQ==","commit":{"author":{"name":"David Miguel","email":"david.miguel@peaks.com","date":"2017-10-15T22:40:41Z"},"committer":{"name":"David Miguel","email":"david.miguel@peaks.com","date":"2017-10-15T22:40:41Z"},"message":"Merge branch 'release-1.2'","tree":{"sha":"7d3292d8efccb104b839caf34a89370bc27abef1","url":"https://api.github.com/repos/davidmigloz/go-bees/git/trees/7d3292d8efccb104b839caf34a89370bc27abef1"},"url":"https://api.github.com/repos/davidmigloz/go-bees/git/commits/a5aaf9016611f9913c21d1f906d7c75df580529a","comment_count":0,"verification":{"verified":false,"reason":"unsigned","signature":null,"payload":null}},"url":"https://api.github.com/repos/davidmigloz/go-bees/commits/a5aaf9016611f9913c21d1f906d7c75df580529a","html_url":"https://github.com/davidmigloz/go-bees/commit/a5aaf9016611f9913c21d1f906d7c75df580529a","comments_url":"https://api.github.com/repos/davidmigloz/go-bees/commits/a5aaf9016611f9913c21d1f906d7c75df580529a/comments","author":{"login":"davidmigloz","id":6546265,"node_id":"MDQ6VXNlcjY1NDYyNjU=","avatar_url":"https://avatars.githubusercontent.com/u/6546265?v=4","gravatar_id":"","url":"https://api.github.com/users/davidmigloz","html_url":"https://github.com/davidmigloz","followers_url":"https://api.github.com/users/davidmigloz/followers","following_url":"https://api.github.com/users/davidmigloz/following{/other_user}","gists_url":"https://api.github.com/users/davidmigloz/gists{/gist_id}","starred_url":"https://api.github.com/users/davidmigloz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/davidmigloz/subscriptions","organizations_url":"https://api.github.com/users/davidmigloz/orgs","repos_url":"https://api.github.com/users/davidmigloz/repos","events_url":"https://api.github.com/users/davidmigloz/events{/privacy}","received_events_url":"https://api.github.com/users/davidmigloz/received_events","type":"User","site_admin":false},"committer":{"login":"davidmigloz","id":6546265,"node_id":"MDQ6VXNlcjY1NDYyNjU=","avatar_url":"https://avatars.githubusercontent.com/u/6546265?v=4","gravatar_id":"","url":"https://api.github.com/users/davidmigloz","html_url":"https://github.com/davidmigloz","followers_url":"https://api.github.com/users/davidmigloz/followers","following_url":"https://api.github.com/users/davidmigloz/following{/other_user}","gists_url":"https://api.github.com/users/davidmigloz/gists{/gist_id}","starred_url":"https://api.github.com/users/davidmigloz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/davidmigloz/subscriptions","organizations_url":"https://api.github.com/users/davidmigloz/orgs","repos_url":"https://api.github.com/users/davidmigloz/repos","events_url":"https://api.github.com/users/davidmigloz/events{/privacy}","received_events_url":"https://api.github.com/users/davidmigloz/received_events","type":"User","site_admin":false},"parents":[{"sha":"fa0a5e28dd33779806b2644876516511caf8f948","url":"https://api.github.com/repos/davidmigloz/go-bees/commits/fa0a5e28dd33779806b2644876516511caf8f948","html_url":"https://github.com/davidmigloz/go-bees/commit/fa0a5e28dd33779806b2644876516511caf8f948"},{"sha":"14a4462b4bc65d2e319c6a22a2aea3892e218748","url":"https://api.github.com/repos/davidmigloz/go-bees/commits/14a4462b4bc65d2e319c6a22a2aea3892e218748","html_url":"https://github.com/davidmigloz/go-bees/commit/14a4462b4bc65d2e319c6a22a2aea3892e218748"}]}
