### ISSUE TITLE
Apply feedback Sprint 2

### ISSUE THREAD

**Issue by lfx1001** [lfx1001/avrela#60]
- [x] Theorical concepts - add virtual labs dedicated section
- [x] Apply cites in the right sentence position
- [x] Add Important Project Aspects - Github workflow
- [x] Divide 'GitHub'  section in subsections

**Comment by clopezno** [comment]
Revisión con comentarios pdf [memoriaclopezno.pdf](https://github.com/lfx1001/avrela/files/9980880/memoriaclopezno.pdf)
