### ISSUE TITLE
Theoretical concepts - Jaro-Winkler distance

### ISSUE THREAD

**Issue by lfx1001** [lfx1001/avrela#84]
Useful information:

- https://srinivas-kulkarni.medium.com/jaro-winkler-vs-levenshtein-distance-2eab21832fd6

**Comment by clopezno** [comment]
I attach a pdf with the revised report. Good effort
[memoriaSimulacion.pdf](https://github.com/lfx1001/avrela/files/11497706/memoriaSimulacion.pdf)
